name: build
on: 
  - push
  - pull_request
  paths:
  - refl_maths/*

jobs: 
  build:
    name: Create Paper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Testing
        uses: snakemake/snakemake-github-action@v1.9.0
        with:
          directory: './'
          snakefile: 'Snakefile'
          args: '--cores 1 '
          stagein: |
            apt-get -qq update && apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-publishers texlive-science-doc texlive-science
            pip install --user matplotlib==3.2.0 emcee numpy scipy seaborn refnx
            cd refl_maths
      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          add: refl_maths/*.pdf
          author_name: Github Actions
          author_email: andrew.mccluskey@diamond.ac.uk
          message: "Paper Built"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
